DIR = $(PWD)
MAKE_DIR = $(DIR)/src/thread_project

INC_SRCH_PATH += -I$(MAKE_DIR)/makefile_thread

all:
	@$(MAKE) -C $(MAKE_DIR) -f makefile_thread

clean:
	@$(MAKE) -C $(MAKE_DIR) -f makefile_thread clean


