DIR = $(PWD)
MAKE_DIR = $(DIR)/mkfiles


all: scalar

.PHONY: scalar
scalar:
	@$(MAKE) -C $(MAKE_DIR) -f makefile_scalar

.PHONY:scalar_clean
scalar_clean:
	@$(MAKE) -C $(MAKE_DIR) -f makefile_scalar clean

