######################################################################
# Automatically generated by qmake (3.0) Mon Feb 15 09:52:20 2021
######################################################################

TEMPLATE = app
TARGET = graph
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += dialog.h mainwin.h
SOURCES += dialog.cpp main.cpp mainwin.cpp
