######################################################################
# Automatically generated by qmake (3.0) Wed Feb 17 09:30:49 2021
######################################################################

TEMPLATE = app
TARGET = graph
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += dialog.h mainwin.h
SOURCES += dialog.cpp main.cpp mainwin.cpp
