######################################################################
# Automatically generated by qmake (3.0) Wed Feb 10 10:40:10 2021
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += dialog.h mainwin.h
SOURCES += dialog.cpp main.cpp mainwin.cpp
