MKF_DIR=./mkf

subsystem:
	$(MAKE) -C $(MKF_DIR) -f makefile_calc
	$(MAKE) -C $(MKF_DIR) -f makefile_rect
	$(MAKE) -C $(MKF_DIR) -f makefile_grade
	$(MAKE) -C $(MKF_DIR) -f makefile_inverse
	$(MAKE) -C $(MKF_DIR) -f makefile_minmax
	$(MAKE) -C $(MKF_DIR) -f makefile_main	
	$(MAKE) -C $(MKF_DIR) -f makefile_guess
	$(MAKE) -C $(MKF_DIR) -f makefile_gcd
	$(MAKE) -C $(MKF_DIR) -f makefile_occurance
clean:
	$(MAKE) -C $(MKF_DIR) -f makefile_calc clean
	$(MAKE) -C $(MKF_DIR) -f makefile_rect clean
	$(MAKE) -C $(MKF_DIR) -f makefile_grade clean
	$(MAKE) -C $(MKF_DIR) -f makefile_inverse clean
	$(MAKE) -C $(MKF_DIR) -f makefile_minmax clean
	$(MAKE) -C $(MKF_DIR) -f makefile_main clean
	$(MAKE) -C $(MKF_DIR) -f makefile_guess clean
	$(MAKE) -C $(MKF_DIR) -f makefile_gcd clean
	$(MAKE) -C $(MKF_DIR) -f makefile_occurance clean
