#! /usr/bin/python3

number1=int(input("first number "))
number2=int(input("second number "))
string1=str(input("str1 number "))
string2=str(input("str2 number "))

if number1 > number2:
    print("number1 is greater than number2")
elif number1 < number2:
    print("number2 is greater than number1")
else:
    print("number1 and number2 are equal")

print()
