######################################################################
# Automatically generated by qmake (3.0) Fri Feb 12 17:23:19 2021
######################################################################

TEMPLATE = app
TARGET = aa
INCLUDEPATH += .
QT += widgets
# Input
SOURCES += aa.cpp
